// Autogenerated from Pigeon (v12.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct TicketData {
  var name: String
  var imageUrl: String
  var ticketNumber: String
  var type: String
  var seat: String

  static func fromList(_ list: [Any?]) -> TicketData? {
    let name = list[0] as! String
    let imageUrl = list[1] as! String
    let ticketNumber = list[2] as! String
    let type = list[3] as! String
    let seat = list[4] as! String

    return TicketData(
      name: name,
      imageUrl: imageUrl,
      ticketNumber: ticketNumber,
      type: type,
      seat: seat
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      imageUrl,
      ticketNumber,
      type,
      seat,
    ]
  }
}

private class TicketHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return TicketData.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class TicketHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TicketData {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TicketHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TicketHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TicketHostApiCodecWriter(data: data)
  }
}

class TicketHostApiCodec: FlutterStandardMessageCodec {
  static let shared = TicketHostApiCodec(readerWriter: TicketHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TicketHostApi {
  func sendTicketData(ticketData: TicketData, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TicketHostApiSetup {
  /// The codec used by TicketHostApi.
  static var codec: FlutterStandardMessageCodec { TicketHostApiCodec.shared }
  /// Sets up an instance of `TicketHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TicketHostApi?) {
    let sendTicketDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hotel_ticket.TicketHostApi.sendTicketData", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTicketDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let ticketDataArg = args[0] as! TicketData
        api.sendTicketData(ticketData: ticketDataArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      sendTicketDataChannel.setMessageHandler(nil)
    }
  }
}
